version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: script/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: script/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: script/start_server.sh
    - location: script/create_test_db.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: script/stop_server.sh
      timeout: 300
      runas: root
